[tool.ruff]
line-length = 120
target-version = "py312"
lint.select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "SIM", # flake8-simplify
    "I", # isort
]
exclude = [
    "migrations",
]
src = ["dreiattest"]

[tool.ruff.format]
exclude = ["*.pyi", ".yaml"]

[tool.ruff.lint.isort]
known-first-party = ["dreiattest",]

[tool.ruff.lint.per-file-ignores]
"Pipfile.lock" = ["ALL"]

[tool.pytest.ini_options]
testpaths = "tests"
python_files = "tests.py test_*.py *_tests.py"
DJANGO_SETTINGS_MODULE = "dreiattest.settings"
addopts = [
    "--import-mode=importlib",
    "--reuse-db"  # because our local user is not allowed to create DBs
]
