from django.conf import settings

DREIATTEST_BASE_URL = getattr(settings, 'DREIATTEST_BASE_URL', 'dreiattest/')
DREIATTEST_UID_HEADER = getattr(settings, 'DREIATTEST_UID_HEADER', 'HTTP_DREIATTEST_UID')
DREIATTEST_SIGNATURE_HEADER = getattr(settings, 'DREIATTEST_SIGNATURE_HEADER', 'HTTP_DREIATTEST_SIGNATURE')
DREIATTEST_NONCE_HEADER = getattr(settings, 'DREIATTEST_NONCE_HEADER', 'HTTP_DREIATTEST_NONCE')
DREIATTEST_USER_HEADERS = getattr(settings, 'DREIATTEST_USER_HEADERS', 'HTTP_DREIATTEST_USER_HEADERS')

DREIATTEST_APPLE_APPID = getattr(settings, 'DREIATTEST_APPLE_APPID', None)
DREIATTEST_PRODUCTION = getattr(settings, 'DREIATTEST_PRODUCTION', True)
