# Generated by Django 3.1.6 on 2021-02-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreiattest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('session_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='key',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dreiattest.devicesession'),
        ),
        migrations.AlterField(
            model_name='nonce',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dreiattest.devicesession'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
