# Generated by Django 3.1.6 on 2021-02-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreiattest', '0002_auto_20210225_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesession',
            name='session_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterIndexTogether(
            name='devicesession',
            index_together={('user_id', 'session_id')},
        ),
    ]
