# Generated by Django 3.1.6 on 2021-02-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreiattest', '0003_auto_20210225_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='user',
            new_name='device_session',
        ),
        migrations.RenameField(
            model_name='nonce',
            old_name='user',
            new_name='device_session',
        ),
    ]
