# Generated by Django 2.2.24 on 2021-09-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreiattest', '0004_auto_20210225_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='driver',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
